"""create ai module

Revision ID: 1dc325701d31
Revises: 4ab05ae851a0
Create Date: 2026-07-02 18:38:42.401978

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "1dc325701d31"
down_revision: Union[str, Sequence[str], None] = "4ab05ae851a0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
