"""add sector column to workspaces

Revision ID: 21cb47cf6a8b
Revises: 1235316d9aa7
Create Date: 2026-07-03 00:30:49.718676

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21cb47cf6a8b"
down_revision: Union[str, Sequence[str], None] = "1235316d9aa7"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    sector_enum = sa.Enum(
        "retail", "service", "education", "agriculture", name="sector_enum"
    )
    sector_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "workspaces",
        sa.Column("sector", sector_enum, server_default="retail", nullable=False),
    )
    op.create_index(
        op.f("ix_workspaces_sector"), "workspaces", ["sector"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_workspaces_sector"), table_name="workspaces")
    op.drop_column("workspaces", "sector")
    sa.Enum(name="sector_enum").drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
