"""create forecasting module

Revision ID: 4ab05ae851a0
Revises: 6a3e29e2dc44
Create Date: 2026-07-02 18:32:16.863884

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "4ab05ae851a0"
down_revision: Union[str, Sequence[str], None] = "6a3e29e2dc44"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_conversations",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column(
            "model_name",
            sa.Enum(
                "GPT-4o",
                "GPT-4.1",
                "GPT-5",
                "Claude",
                "Gemini",
                "Llama",
                "Custom",
                name="ai_model_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("Active", "Archived", name="ai_conversation_status_enum"),
            server_default="Active",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_ai_conversations_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ai_conversations_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_ai_conversations_updated_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_ai_conversations_user_id_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_ai_conversations_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_conversations")),
    )
    op.create_index(
        op.f("ix_ai_conversations_organization_id"),
        "ai_conversations",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_conversations_user_id"),
        "ai_conversations",
        ["user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_conversations_workspace_id"),
        "ai_conversations",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "ai_messages",
        sa.Column("conversation_id", sa.UUID(), nullable=False),
        sa.Column(
            "sender_type",
            sa.Enum("User", "AI", name="ai_message_sender_enum"),
            nullable=False,
        ),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("tokens_used", sa.Integer(), server_default="0", nullable=False),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["conversation_id"],
            ["ai_conversations.id"],
            name=op.f("fk_ai_messages_conversation_id_ai_conversations"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_messages")),
    )
    op.create_index(
        op.f("ix_ai_messages_conversation_id"),
        "ai_messages",
        ["conversation_id"],
        unique=False,
    )
    op.create_table(
        "forecast_models",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("model_name", sa.String(length=100), nullable=False),
        sa.Column(
            "algorithm",
            sa.Enum(
                "Linear Regression",
                "Random Forest",
                "XGBoost",
                "ARIMA",
                "Prophet",
                "LSTM",
                name="forecast_algorithm_enum",
            ),
            nullable=False,
        ),
        sa.Column("target_column", sa.String(length=100), nullable=False),
        sa.Column("parameters", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("accuracy", sa.Numeric(precision=5, scale=2), nullable=True),
        sa.Column(
            "status",
            sa.Enum("Active", "Inactive", name="forecast_model_status_enum"),
            server_default="Active",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_forecast_models_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_forecast_models_dataset_id_datasets"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_forecast_models_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_forecast_models_updated_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_models")),
    )
    op.create_index(
        op.f("ix_forecast_models_dataset_id"),
        "forecast_models",
        ["dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_forecast_models_organization_id"),
        "forecast_models",
        ["organization_id"],
        unique=False,
    )
    op.create_table(
        "forecast_results",
        sa.Column("forecast_model_id", sa.UUID(), nullable=False),
        sa.Column("prediction_date", sa.Date(), nullable=False),
        sa.Column("predicted_value", sa.Numeric(precision=18, scale=4), nullable=False),
        sa.Column(
            "confidence_interval",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
        ),
        sa.Column("actual_value", sa.Numeric(precision=18, scale=4), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["forecast_model_id"],
            ["forecast_models.id"],
            name=op.f("fk_forecast_results_forecast_model_id_forecast_models"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_forecast_results")),
    )
    op.create_index(
        op.f("ix_forecast_results_forecast_model_id"),
        "forecast_results",
        ["forecast_model_id"],
        unique=False,
    )
    op.create_table(
        "ai_recommendations",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("analytics_result_id", sa.UUID(), nullable=False),
        sa.Column(
            "recommendation_type",
            sa.Enum(
                "Insight",
                "Optimization",
                "Warning",
                "Opportunity",
                "Forecast",
                name="ai_recommendation_type_enum",
            ),
            nullable=False,
        ),
        sa.Column("recommendation", sa.Text(), nullable=False),
        sa.Column("confidence_score", sa.Numeric(precision=5, scale=2), nullable=False),
        sa.Column(
            "priority",
            sa.Enum("High", "Medium", "Low", name="ai_recommendation_priority_enum"),
            nullable=False,
        ),
        sa.Column("is_applied", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["analytics_result_id"],
            ["analysis_results.id"],
            name=op.f("fk_ai_recommendations_analytics_result_id_analysis_results"),
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_ai_recommendations_created_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_ai_recommendations_dataset_id_datasets"),
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_ai_recommendations_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_ai_recommendations_updated_by_users"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_recommendations")),
    )
    op.create_index(
        op.f("ix_ai_recommendations_analytics_result_id"),
        "ai_recommendations",
        ["analytics_result_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_recommendations_dataset_id"),
        "ai_recommendations",
        ["dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_ai_recommendations_organization_id"),
        "ai_recommendations",
        ["organization_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ai_recommendations_organization_id"), table_name="ai_recommendations"
    )
    op.drop_index(
        op.f("ix_ai_recommendations_dataset_id"), table_name="ai_recommendations"
    )
    op.drop_index(
        op.f("ix_ai_recommendations_analytics_result_id"),
        table_name="ai_recommendations",
    )
    op.drop_table("ai_recommendations")
    op.drop_index(
        op.f("ix_forecast_results_forecast_model_id"), table_name="forecast_results"
    )
    op.drop_table("forecast_results")
    op.drop_index(
        op.f("ix_forecast_models_organization_id"), table_name="forecast_models"
    )
    op.drop_index(op.f("ix_forecast_models_dataset_id"), table_name="forecast_models")
    op.drop_table("forecast_models")
    op.drop_index(op.f("ix_ai_messages_conversation_id"), table_name="ai_messages")
    op.drop_table("ai_messages")
    op.drop_index(
        op.f("ix_ai_conversations_workspace_id"), table_name="ai_conversations"
    )
    op.drop_index(op.f("ix_ai_conversations_user_id"), table_name="ai_conversations")
    op.drop_index(
        op.f("ix_ai_conversations_organization_id"), table_name="ai_conversations"
    )
    op.drop_table("ai_conversations")
    # ### end Alembic commands ###
