"""phase3: records, thresholds, decision-card fields on ai_recommendations

Revision ID: 56611151632f
Revises: 21cb47cf6a8b
Create Date: 2026-07-03 08:49:51.452965

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "56611151632f"
down_revision: Union[str, Sequence[str], None] = "21cb47cf6a8b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thresholds",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("metric_key", sa.String(length=64), nullable=False),
        sa.Column("label", sa.String(length=255), nullable=False),
        sa.Column("warning_value", sa.Numeric(), nullable=True),
        sa.Column("critical_value", sa.Numeric(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_thresholds_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_thresholds_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_thresholds")),
        sa.UniqueConstraint(
            "workspace_id", "metric_key", name="uq_thresholds_workspace_metric"
        ),
    )
    op.create_index(
        op.f("ix_thresholds_organization_id"),
        "thresholds",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_thresholds_workspace_id"), "thresholds", ["workspace_id"], unique=False
    )
    op.create_table(
        "records",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("data", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("recorded_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"], ["datasets.id"], name=op.f("fk_records_dataset_id_datasets")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_records_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_records_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_records")),
    )
    op.create_index(
        op.f("ix_records_dataset_id"), "records", ["dataset_id"], unique=False
    )
    op.create_index(
        op.f("ix_records_organization_id"), "records", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_records_workspace_id"), "records", ["workspace_id"], unique=False
    )
    op.add_column(
        "ai_recommendations", sa.Column("workspace_id", sa.UUID(), nullable=True)
    )
    op.add_column(
        "ai_recommendations", sa.Column("title", sa.String(length=255), nullable=True)
    )
    decision_status_enum = sa.Enum(
        "pending", "approved", "rejected", name="decision_status_enum"
    )
    decision_status_enum.create(op.get_bind(), checkfirst=True)
    op.add_column(
        "ai_recommendations",
        sa.Column(
            "decision_status",
            decision_status_enum,
            server_default="pending",
            nullable=False,
        ),
    )
    op.add_column(
        "ai_recommendations", sa.Column("resolved_by", sa.UUID(), nullable=True)
    )
    op.add_column(
        "ai_recommendations",
        sa.Column("resolved_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.alter_column(
        "ai_recommendations", "dataset_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "ai_recommendations",
        "analytics_result_id",
        existing_type=sa.UUID(),
        nullable=True,
    )
    op.alter_column(
        "ai_recommendations", "recommendation", existing_type=sa.TEXT(), nullable=True
    )
    op.alter_column(
        "ai_recommendations",
        "confidence_score",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=True,
    )
    op.create_index(
        op.f("ix_ai_recommendations_workspace_id"),
        "ai_recommendations",
        ["workspace_id"],
        unique=False,
    )
    op.create_foreign_key(
        op.f("fk_ai_recommendations_resolved_by_users"),
        "ai_recommendations",
        "users",
        ["resolved_by"],
        ["id"],
    )
    op.create_foreign_key(
        op.f("fk_ai_recommendations_workspace_id_workspaces"),
        "ai_recommendations",
        "workspaces",
        ["workspace_id"],
        ["id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("fk_ai_recommendations_workspace_id_workspaces"),
        "ai_recommendations",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("fk_ai_recommendations_resolved_by_users"),
        "ai_recommendations",
        type_="foreignkey",
    )
    op.drop_index(
        op.f("ix_ai_recommendations_workspace_id"), table_name="ai_recommendations"
    )
    op.alter_column(
        "ai_recommendations",
        "confidence_score",
        existing_type=sa.NUMERIC(precision=5, scale=2),
        nullable=False,
    )
    op.alter_column(
        "ai_recommendations", "recommendation", existing_type=sa.TEXT(), nullable=False
    )
    op.alter_column(
        "ai_recommendations",
        "analytics_result_id",
        existing_type=sa.UUID(),
        nullable=False,
    )
    op.alter_column(
        "ai_recommendations", "dataset_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("ai_recommendations", "resolved_at")
    op.drop_column("ai_recommendations", "resolved_by")
    op.drop_column("ai_recommendations", "decision_status")
    sa.Enum(name="decision_status_enum").drop(op.get_bind(), checkfirst=True)
    op.drop_column("ai_recommendations", "title")
    op.drop_column("ai_recommendations", "workspace_id")
    op.drop_index(op.f("ix_records_workspace_id"), table_name="records")
    op.drop_index(op.f("ix_records_organization_id"), table_name="records")
    op.drop_index(op.f("ix_records_dataset_id"), table_name="records")
    op.drop_table("records")
    op.drop_index(op.f("ix_thresholds_workspace_id"), table_name="thresholds")
    op.drop_index(op.f("ix_thresholds_organization_id"), table_name="thresholds")
    op.drop_table("thresholds")
    # ### end Alembic commands ###
