"""add_memory_columns_to_ai_conversations

Revision ID: 8cb83dba9001
Revises: 66b882926fe5
Create Date: 2026-07-04 04:41:26.561084

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "8cb83dba9001"
down_revision: Union[str, Sequence[str], None] = "66b882926fe5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("ai_conversations", sa.Column("summary", sa.Text(), nullable=True))
    op.add_column(
        "ai_conversations",
        sa.Column("total_messages", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "ai_conversations",
        sa.Column("total_tokens", sa.Integer(), server_default="0", nullable=False),
    )
    op.add_column(
        "ai_conversations",
        sa.Column("last_message_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.add_column(
        "ai_conversations",
        sa.Column("last_summary_at", sa.DateTime(timezone=True), nullable=True),
    )
    op.create_index(
        op.f("ix_ai_conversations_last_message_at"),
        "ai_conversations",
        ["last_message_at"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_ai_conversations_last_message_at"), table_name="ai_conversations"
    )
    op.drop_column("ai_conversations", "last_summary_at")
    op.drop_column("ai_conversations", "last_message_at")
    op.drop_column("ai_conversations", "total_tokens")
    op.drop_column("ai_conversations", "total_messages")
    op.drop_column("ai_conversations", "summary")
    # ### end Alembic commands ###
