"""create analytics module

Revision ID: 9ffc675c09d0
Revises: ce7c6d9107fe
Create Date: 2026-07-02 16:35:46.114685

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "9ffc675c09d0"
down_revision: Union[str, Sequence[str], None] = "ce7c6d9107fe"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "analysis_jobs",
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("initiated_by", sa.UUID(), nullable=False),
        sa.Column(
            "job_type",
            sa.Enum(
                "Descriptive Analysis",
                "Diagnostic Analysis",
                "Predictive Analysis",
                "Prescriptive Analysis",
                "Forecasting",
                "Anomaly Detection",
                name="analysis_job_type_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "Pending",
                "Running",
                "Completed",
                "Failed",
                "Cancelled",
                name="analysis_job_status_enum",
            ),
            server_default="Pending",
            nullable=False,
        ),
        sa.Column("progress", sa.Integer(), server_default="0", nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("completed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_analysis_jobs_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_analysis_jobs_dataset_id_datasets"),
        ),
        sa.ForeignKeyConstraint(
            ["initiated_by"],
            ["users.id"],
            name=op.f("fk_analysis_jobs_initiated_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_analysis_jobs_updated_by_users")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_jobs")),
    )
    op.create_index(
        op.f("ix_analysis_jobs_dataset_id"),
        "analysis_jobs",
        ["dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_jobs_initiated_by"),
        "analysis_jobs",
        ["initiated_by"],
        unique=False,
    )
    op.create_table(
        "analysis_results",
        sa.Column("job_id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("metric_name", sa.String(length=255), nullable=False),
        sa.Column(
            "metric_value", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "visualization_type",
            sa.Enum(
                "Bar",
                "Line",
                "Pie",
                "Scatter",
                "Histogram",
                "Heatmap",
                "KPI",
                "Table",
                name="visualization_type_enum",
            ),
            nullable=True,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_analysis_results_dataset_id_datasets"),
        ),
        sa.ForeignKeyConstraint(
            ["job_id"],
            ["analysis_jobs.id"],
            name=op.f("fk_analysis_results_job_id_analysis_jobs"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analysis_results")),
    )
    op.create_index(
        op.f("ix_analysis_results_dataset_id"),
        "analysis_results",
        ["dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_analysis_results_job_id"), "analysis_results", ["job_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_analysis_results_job_id"), table_name="analysis_results")
    op.drop_index(op.f("ix_analysis_results_dataset_id"), table_name="analysis_results")
    op.drop_table("analysis_results")
    op.drop_index(op.f("ix_analysis_jobs_initiated_by"), table_name="analysis_jobs")
    op.drop_index(op.f("ix_analysis_jobs_dataset_id"), table_name="analysis_jobs")
    op.drop_table("analysis_jobs")
    # ### end Alembic commands ###
