"""create reporting module

Revision ID: a32f4c29c3e6
Revises: 1dc325701d31
Create Date: 2026-07-02 18:55:56.501281

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a32f4c29c3e6"
down_revision: Union[str, Sequence[str], None] = "1dc325701d31"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "reports",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("report_name", sa.String(length=255), nullable=False),
        sa.Column(
            "report_type",
            sa.Enum(
                "Dashboard",
                "Analytics",
                "Forecast",
                "Dataset",
                "Custom",
                name="report_type_enum",
            ),
            nullable=False,
        ),
        sa.Column(
            "report_config", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column(
            "status",
            sa.Enum("Active", "Archived", name="report_status_enum"),
            server_default="Active",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"], ["users.id"], name=op.f("fk_reports_created_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_reports_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"], ["users.id"], name=op.f("fk_reports_updated_by_users")
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_reports_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_reports")),
    )
    op.create_index(
        op.f("ix_reports_organization_id"), "reports", ["organization_id"], unique=False
    )
    op.create_index(
        op.f("ix_reports_workspace_id"), "reports", ["workspace_id"], unique=False
    )
    op.create_table(
        "report_exports",
        sa.Column("report_id", sa.UUID(), nullable=False),
        sa.Column("exported_by", sa.UUID(), nullable=False),
        sa.Column(
            "export_format",
            sa.Enum("PDF", "XLSX", "CSV", name="export_format_enum"),
            nullable=False,
        ),
        sa.Column("file_path", sa.Text(), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["exported_by"],
            ["users.id"],
            name=op.f("fk_report_exports_exported_by_users"),
        ),
        sa.ForeignKeyConstraint(
            ["report_id"],
            ["reports.id"],
            name=op.f("fk_report_exports_report_id_reports"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_report_exports")),
    )
    op.create_index(
        op.f("ix_report_exports_exported_by"),
        "report_exports",
        ["exported_by"],
        unique=False,
    )
    op.create_index(
        op.f("ix_report_exports_report_id"),
        "report_exports",
        ["report_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_report_exports_report_id"), table_name="report_exports")
    op.drop_index(op.f("ix_report_exports_exported_by"), table_name="report_exports")
    op.drop_table("report_exports")
    op.drop_index(op.f("ix_reports_workspace_id"), table_name="reports")
    op.drop_index(op.f("ix_reports_organization_id"), table_name="reports")
    op.drop_table("reports")
    # ### end Alembic commands ###
