"""create_vector_chunks_table

Revision ID: bb32bbfc013a
Revises: 8cb83dba9001
Create Date: 2026-07-04 11:41:23.985205

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import pgvector

# revision identifiers, used by Alembic.
revision: str = "bb32bbfc013a"
down_revision: Union[str, Sequence[str], None] = "8cb83dba9001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Ensure pgvector extension is available in PostgreSQL
    op.execute("CREATE EXTENSION IF NOT EXISTS vector")

    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "vector_chunks",
        sa.Column("organization_id", sa.UUID(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("dataset_id", sa.UUID(), nullable=False),
        sa.Column("document_id", sa.UUID(), nullable=True),
        sa.Column("record_id", sa.UUID(), nullable=True),
        sa.Column("content", sa.Text(), nullable=False),
        sa.Column(
            "embedding", pgvector.sqlalchemy.vector.VECTOR(dim=384), nullable=False
        ),
        sa.Column(
            "metadata_json", postgresql.JSONB(astext_type=sa.Text()), nullable=False
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.ForeignKeyConstraint(
            ["dataset_id"],
            ["datasets.id"],
            name=op.f("fk_vector_chunks_dataset_id_datasets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organization_id"],
            ["organizations.id"],
            name=op.f("fk_vector_chunks_organization_id_organizations"),
        ),
        sa.ForeignKeyConstraint(
            ["record_id"],
            ["records.id"],
            name=op.f("fk_vector_chunks_record_id_records"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_vector_chunks_workspace_id_workspaces"),
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_vector_chunks")),
    )
    op.create_index(
        op.f("ix_vector_chunks_dataset_id"),
        "vector_chunks",
        ["dataset_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vector_chunks_document_id"),
        "vector_chunks",
        ["document_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vector_chunks_organization_id"),
        "vector_chunks",
        ["organization_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_vector_chunks_record_id"), "vector_chunks", ["record_id"], unique=False
    )
    op.create_index(
        op.f("ix_vector_chunks_workspace_id"),
        "vector_chunks",
        ["workspace_id"],
        unique=False,
    )

    # Create the high-performance HNSW index on the vector embedding column
    op.execute(
        "CREATE INDEX idx_vector_chunks_embedding ON vector_chunks USING hnsw (embedding vector_cosine_ops)"
    )

    op.add_column(
        "ai_recommendations",
        sa.Column(
            "metadata_json",
            postgresql.JSONB(astext_type=sa.Text()).with_variant(sa.JSON(), "sqlite"),
            nullable=True,
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("ai_recommendations", "metadata_json")
    op.execute("DROP INDEX IF EXISTS idx_vector_chunks_embedding")
    op.drop_index(op.f("ix_vector_chunks_workspace_id"), table_name="vector_chunks")
    op.drop_index(op.f("ix_vector_chunks_record_id"), table_name="vector_chunks")
    op.drop_index(op.f("ix_vector_chunks_organization_id"), table_name="vector_chunks")
    op.drop_index(op.f("ix_vector_chunks_document_id"), table_name="vector_chunks")
    op.drop_index(op.f("ix_vector_chunks_dataset_id"), table_name="vector_chunks")
    op.drop_table("vector_chunks")
    # ### end Alembic commands ###
