"""create organizations table

Revision ID: d54fbaf32f17
Revises:
Create Date: 2026-07-02 10:17:31.380247

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "d54fbaf32f17"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "organizations",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("slug", sa.String(length=100), nullable=False),
        sa.Column("industry", sa.String(length=100), nullable=False),
        sa.Column(
            "subscription_plan",
            sa.Enum("Free", "Pro", "Enterprise", name="subscription_plan_enum"),
            server_default="Free",
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum("Active", "Inactive", "Suspended", name="organization_status_enum"),
            server_default="Active",
            nullable=False,
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("is_deleted", sa.Boolean(), server_default="false", nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_organizations")),
        sa.UniqueConstraint("slug", name=op.f("uq_organizations_slug")),
    )
    op.create_index(
        "ix_organizations_industry", "organizations", ["industry"], unique=False
    )
    op.create_index(
        "ix_organizations_status", "organizations", ["status"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_organizations_status", table_name="organizations")
    op.drop_index("ix_organizations_industry", table_name="organizations")
    op.drop_table("organizations")
    # ### end Alembic commands ###
